name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: init system
      run: sudo apt update -y && sudo apt install wget build-essential tar
    - name: build python
      run: wget https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tgz
    - name: b2 p
      run: tar -zxvf Python-3.6.10.tgz
    - name: b3 p
      run: cd Python-3.6.10
    - name: b3 p
      run: ls -alh
    - name: b4 p
      run: ./configure --prefix=/usr/local/python3
      working-directory: Python-3.6.10
    - name: b5 p
      run: make -j
      working-directory: Python-3.6.10
    - name: b6 p
      run: sudo make install
      working-directory: Python-3.6.10
    - name: build boost
      run: wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz
    - name: build boost
      run: tar -zxvf boost_1_66_0.tar.gz
    - name: build boost
      run: cd boost_1_66_0
    - name: build boost
      run: ./bootstrap.sh --with-python=/usr/local/python3
      working-directory: boost_1_66_0
    - name: build boost
      run: ./b2 --toolset=gcc-7  --with-python include="/usr/local/python3/include/python3.6m/" --with-thread --with-date_time  --with-chrono
      working-directory: boost_1_66_0
    - name: build boost
      run: ls -alh stage
      working-directory: boost_1_66_0
    - name: prebuild xtp
      run: mkdir build
      working-directory: source/Linux/xtp_python3_2.2.15.1/
    - name: build xtp
      run: bash build.sh
      working-directory: source/Linux/xtp_python3_2.2.15.1/
  
